# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-11-17 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('name', models.CharField(max_length=250)),
                ('surname', models.CharField(max_length=250)),
                ('patronymic', models.CharField(max_length=250)),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'verbose_name': '\u043a\u043b\u0438\u0435\u043d\u0442',
                'verbose_name_plural': '\u043a\u043b\u0438\u0435\u043d\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500, null=True)),
                ('mailing_time', models.DateTimeField(verbose_name='\u0434\u0430\u0442\u0430 \u0438 \u0432\u0440\u0435\u043c\u044f \u043e\u0442\u043f\u0440\u0430\u0432\u043a\u0438')),
                ('client', models.ManyToManyField(to='mail_factory.Client', verbose_name='\u041a\u043b\u0438\u0435\u043d\u0442')),
            ],
            options={
                'verbose_name': '\u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0430',
                'verbose_name_plural': '\u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0438',
            },
        ),
    ]
