# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-11-16 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_factory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglist',
            name='mail',
        ),
        migrations.DeleteModel(
            name='Mail',
        ),
    ]
