# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-11-16 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_factory', '0002_auto_20221116_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='subject',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
