# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-11-17 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mail_factory', '0002_auto_20221117_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='opened',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
