# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-11-16 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_factory', '0002_auto_20221116_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mailinglist',
            name='slug',
        ),
    ]
