# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-11-17 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_factory', '0003_auto_20221117_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
