# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-11-17 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_factory', '0006_auto_20221117_0033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Template',
            new_name='EmailTemplate',
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'verbose_name': '\u0448\u0430\u0431\u043b\u043e\u043d', 'verbose_name_plural': '\u0448\u0430\u0431\u043b\u043e\u043d\u044b'},
        ),
    ]
